GET http://localhost:3000/api/qrcodes

###
GET http://localhost:3000/api/short-links

###

POST http://localhost:3000/api/qrcodes
Content-Type: application/json

{
  "title": "위키피디아 Next.js",
  "url": "https://ko.wikipedia.org/wiki/Next.js"
}

###

GET http://localhost:3000/api/qrcodes/64e616a8b74bbcba6c7fd505


###
GET http://localhost:3000/api/qrcodes/64e613f579ae06a893d88f10

###

PATCH http://localhost:3000/api/qrcodes/64e613f579ae06a893d88f10
Content-Type: application/json

{
  "id":"64e613f579ae06a893d88f10",
  "title": "위키피디아 React.js",
  "url": "https://en.wikipedia.org/wiki/react.js"
}

###

DELETE http://localhost:3000/api/qrcodes/64e613f579ae06a893d88f10

###

POST http://localhost:3000/api/qrcodes/64e616a8b74bbcba6c7fd505